### PR TITLE
Add conda env

### PR DESCRIPTION
**Pull request by h0gan1ee**

### CODE REVIEW

**Comment by eastonman** [comment]
Remove the prefix containing your own path

**Comment by h0gan1ee** [comment]
> Remove the prefix containing your own path

Removed

**Comment by shirok1** [comment]
建议换成 poetry

**Comment by Origami404** [comment]
lgtm

**Review by Origami404 — APPROVED** [review]

**Comment by h0gan1ee** [comment]
> 建议换成 poetry

Idk, but conda is pretty handy and competent.

**Pull request merged**
