### PR TITLE
Add doc wsl-install-guide&update mkdocs.yml

### PR DESCRIPTION
**Pull request by SoraShu**

### CODE REVIEW

**Review by eastonman — CHANGES_REQUESTED** [review]
确定要把图片放git repo里？

**Comment by SoraShu** [comment]
> 确定要把图片放git repo里？

我放图床也行，放仓库碎的可能性比较低。或者我放base64？

**Comment by yukkohzq** [comment]
感觉每个文档弄个分开的文件夹放图片会好一些

**Comment by eastonman** [comment]
我比较倾向于图床
可搞个lug图床？或者单开仓库丢图？

**Comment by h0gan1ee** [comment]
用 webp 格式放仓库其实也问题不大

**Comment by hilaolu** [comment]
I do appreciate all your opinions above. Files in Git repo can be delete completely, though may be a little inconvenient. However, images in repo can be deploy to cloudflare global cdn.

**Comment by h0gan1ee** [comment]
It would be better if 'popular science' is changed to 'Popular Science'.

**Review by eastonman — APPROVED** [review]

**Pull request merged**
